export const sampleSuttas = [
  {
    title: "Goodwill (0) / Mettā Sutta",
    content: `“Monks, for one whose awareness-release through goodwill is cultivated, developed, pursued, given a means of transport, given a grounding, steadied, consolidated, and well-undertaken, eleven benefits can be expected. Which eleven?
              “One sleeps easily, wakes easily, dreams no evil dreams. One is dear to human beings, dear to non-human beings. The devas protect one. Neither fire, poison, nor weapons can touch one. One’s mind gains concentration quickly. One’s complexion is bright. One dies unconfused and, if penetrating no higher, is headed for a Brahmā world.
              “These are the eleven benefits that can be expected for one whose awareness-release through goodwill is cultivated, developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken.”`,
    source: "AN 11:16",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN11_16.html",
    category: "Goodwill",
  },
  {
    title: "Goodwill (1) / Mettā Sutta",
    content: `“Monks, there are these four types of individuals to be found existing in the world. Which four?
              “There is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth—with an awareness imbued with goodwill. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with goodwill: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Devas of Brahmā’s Retinue. The Devas of Brahmā’s Retinue, monks, have a lifespan of an eon. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “And further, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with compassion. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with compassion: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Ābhassara [Radiant] devas. The Ābhassara devas, monks, have a lifespan of two eons. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “And further, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with empathetic joy. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with empathetic joy: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Subhakiṇha [Beautiful Black] devas. The Subhakiṇha devas, monks, have a lifespan of four eons. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “And further, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth—with an awareness imbued with equanimity. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with equanimity: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Vehapphala [Sky-fruit] devas. The Vehapphala devas, monks, have a lifespan of 500 eons. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “These are four types of individuals to be found existing in the world.”`,
    source: "AN 4:125",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN4_125.html",
    category: "Goodwill",
  },
  {
    title: "Goodwill (2) / Mettā Sutta",
    content: `“Monks, there are these four types of individuals to be found existing in the world. Which four?
              “There is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with goodwill. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with goodwill: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “Again, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with compassion. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with compassion: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “Again, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with empathetic joy. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with empathetic joy: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “Again, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with equanimity. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with equanimity: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “These are four types of individuals to be found existing in the world.”`,
    source: "AN 4:126",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN4_126.html",
    category: "Goodwill",
  },
  {
    title: "GoodWill / Mettā Sutta",
    content: `On one occasion the Blessed One was staying among the Koliyans. Now there is a Koliyan town named Haliddavasana. Then, early in the morning, a large number of monks adjusted their lower robes and, taking their bowls & outer robes, went into Haliddavasana for alms. Then the thought occurred to them, “It’s still too early to go for alms in Haliddavasana. Why don’t we go to the park of the wanderers of other sects?”
              So the monks went to the park of the wanderers of other sects. On arrival, they exchanged courteous greetings with the wanderers of other sects. After an exchange of friendly greetings & courtesies, they sat to one side.
              As they were sitting there, the wanderers of other sects said to them, “Friends, Gotama the contemplative teaches the Dhamma to his disciples in this way: ‘Come, monks. Abandoning the five hindrances, the corruptions of awareness that weaken discernment, keep pervading the first direction [the east] with an awareness imbued with goodwill, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with goodwill. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with compassion, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with compassion. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with empathetic joy, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with empathetic joy. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with equanimity, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with equanimity. Abundant, enlarged, immeasurable, without hostility, without ill will.’
              “Now, friends, we too teach our disciples in this way: ‘Come, you friends, abandoning the five hindrances, the corruptions of awareness that weaken discernment, keep pervading the first direction [the east] with an awareness imbued with goodwill, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with goodwill. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with compassion, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with compassion. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with empathetic joy, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with empathetic joy. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with equanimity, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with equanimity. Abundant, enlarged, immeasurable, without hostility, without ill will.’
              “So, friends, what difference, what distinction, what distinguishing factor is there here between Gotama the contemplative and us, when comparing Dhamma teaching with Dhamma teaching, instruction with instruction?”
              Then the monks neither delighted in the words of the wanderers of other sects, nor did they reject them. Without delighting or rejecting, they got up from their seats and left, (thinking,) “We will learn the meaning of these words in the presence of the Blessed One.”
              So, having gone for alms in Haliddavasana, after the meal, returning from their alms round, the monks went to the Blessed One and, on arrival, having bowed down to him, sat to one side. As they were sitting there they [told him what had happened].
              “Monks, when wanderers of other sects speak in that way, they should be addressed in this way: ‘But how, friends, is awareness-release through goodwill developed, what is its destination, what is its excellence, its fruit, & its consummation? How is awareness-release through compassion developed, what is its destination, what is its excellence, its fruit, & its consummation? How is awareness-release through empathetic joy developed, what is its destination, what is its excellence, its fruit, & its consummation? How is awareness-release through equanimity developed, what is its destination, what is its excellence, its fruit, & its consummation?’
              “Being asked in this way, the wanderers of other sects will be unable to respond and, on top of that, will fall into vexation. Why is that? Because it lies beyond their range. Monks, I don’t see anyone in this cosmos with its devas, Māras, & Brahmās, in this generation with its contemplatives & brahmans, its royalty & commonfolk, who would satisfy the mind with their answer to these questions, aside from the Tathāgata, a disciple of the Tathāgata, or one who had heard it from them.
              “And how, monks, is awareness-release through goodwill developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or he may enter & remain in the beautiful liberation. I tell you, monks, awareness-release through goodwill has the beautiful as its excellence, in the case of one who has penetrated to no higher release.
              “And how is awareness-release through compassion developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or, with the complete transcending of perceptions of (physical) form, with the disappearance of perceptions of resistance, and not attending to perceptions of multiplicity, (perceiving,) ‘Infinite space,’ he enters & remains in the sphere of the infinitude of space. I tell you, monks, awareness-release through compassion has the sphere of the infinitude of space as its excellence, in the case of one who has penetrated to no higher release.
              “And how is awareness-release through empathetic joy developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or, with the complete transcending of the sphere of the infinitude of space, (perceiving,) ‘Infinite consciousness,’ he enters & remains in the sphere of the infinitude of consciousness. I tell you, monks, awareness-release through empathetic joy has the sphere of the infinitude of consciousness as its excellence, in the case of one who has penetrated to no higher release.
              “And how is awareness-release through equanimity developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or, with the complete transcending of the sphere of the infinitude of consciousness, (perceiving,) ‘There is nothing,’ he enters & remains in the sphere of nothingness. I tell you, monks, awareness-release through equanimity has the sphere of nothingness as its excellence, in the case of one who has penetrated to no higher release. ”`,
    source: "SN 46:54",
    sourceUrl: "https://www.dhammatalks.org/suttas/SN/SN46_54.html",
    category: "Goodwill",
  },
  {
    title: "Mindfulness of Breathing",
    content: `"Now how is mindfulness of in-&-out breathing developed & pursued so as to be of great fruit, of great benefit?"`,
    source: "MN 118",
    sourceUrl: "https://www.dhammatalks.org/suttas/MN/MN118.html",
    category: "Meditation",
  },
  {
    title: "The Ending of Craving",
    content: `"Monks, there are these four nutriments for the maintenance of beings who have come into being or for the support of those in search of a place to be born. Which four? Physical food, gross or refined; contact as the second; intellectual intention the third; and consciousness the fourth."`,
    source: "SN 12:64",
    sourceUrl: "https://www.dhammatalks.org/suttas/SN/SN12_64.html",
    category: "Core Teachings",
  },
  {
    title: "The Heartwood",
    content: `"Monks, this holy life doesn't have as its reward gain, offerings, & fame, doesn't have as its reward consummation of virtue, doesn't have as its reward consummation of concentration, doesn't have as its reward knowledge & vision, but has as its goal the unshakable deliverance of mind: That is the essence of this holy life, that is its heartwood, that its culmination."`,
    source: "MN 29",
    sourceUrl: "https://www.dhammatalks.org/suttas/MN/MN29.html",
    category: "Core Teachings",
  },
  {
    title: "Mindfulness of Breathing",
    content: `"Now how is mindfulness of in-&-out breathing developed & pursued so as to be of great fruit, of great benefit?"`,
    source: "MN 118",
    sourceUrl: "https://www.dhammatalks.org/suttas/MN/MN118.html",
    category: "Meditation",
  },
  {
    title: "The Ending of Craving",
    content: `"Monks, there are these four nutriments for the maintenance of beings who have come into being or for the support of those in search of a place to be born. Which four? Physical food, gross or refined; contact as the second; intellectual intention the third; and consciousness the fourth."`,
    source: "SN 12:64",
    sourceUrl: "https://www.dhammatalks.org/suttas/SN/SN12_64.html",
    category: "Core Teachings",
  },
  {
    title: "The Heartwood",
    content: `"Monks, this holy life doesn't have as its reward gain, offerings, & fame, doesn't have as its reward consummation of virtue, doesn't have as its reward consummation of concentration, doesn't have as its reward knowledge & vision, but has as its goal the unshakable deliverance of mind: That is the essence of this holy life, that is its heartwood, that its culmination."`,
    source: "MN 29",
    sourceUrl: "https://www.dhammatalks.org/suttas/MN/MN29.html",
    category: "Core Teachings",
  },
  {
    title: "Mindfulness of Breathing",
    content: `"Now how is mindfulness of in-&-out breathing developed & pursued so as to be of great fruit, of great benefit?"`,
    source: "MN 118",
    sourceUrl: "https://www.dhammatalks.org/suttas/MN/MN118.html",
    category: "Meditation",
  },
];
