export const sampleSuttas = [
  {
    title: "Goodwill (0) / Mettā Sutta",
    content: `“Monks, for one whose awareness-release through goodwill is cultivated, developed, pursued, given a means of transport, given a grounding, steadied, consolidated, and well-undertaken, eleven benefits can be expected. Which eleven?
              “One sleeps easily, wakes easily, dreams no evil dreams. One is dear to human beings, dear to non-human beings. The devas protect one. Neither fire, poison, nor weapons can touch one. One’s mind gains concentration quickly. One’s complexion is bright. One dies unconfused and, if penetrating no higher, is headed for a Brahmā world.
              “These are the eleven benefits that can be expected for one whose awareness-release through goodwill is cultivated, developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken.”`,
    source: "AN 11:16",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN11_16.html",
    category: "Goodwill",
  },
  {
    title: "Goodwill (1) / Mettā Sutta",
    content: `“Monks, there are these four types of individuals to be found existing in the world. Which four?
              “There is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth—with an awareness imbued with goodwill. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with goodwill: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Devas of Brahmā’s Retinue. The Devas of Brahmā’s Retinue, monks, have a lifespan of an eon. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “And further, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with compassion. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with compassion: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Ābhassara [Radiant] devas. The Ābhassara devas, monks, have a lifespan of two eons. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “And further, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with empathetic joy. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with empathetic joy: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Subhakiṇha [Beautiful Black] devas. The Subhakiṇha devas, monks, have a lifespan of four eons. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “And further, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth—with an awareness imbued with equanimity. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with equanimity: abundant, expansive, immeasurable, free from hostility, free from ill will. He savors that, longs for that, finds satisfaction through that. Staying there, fixed on that, dwelling there often, not falling away from that, then when he dies he reappears in conjunction with the Vehapphala [Sky-fruit] devas. The Vehapphala devas, monks, have a lifespan of 500 eons. A run-of-the-mill person having stayed there, having used up all the lifespan of those devas, goes to hell, to the animal womb, to the state of the hungry ghosts. But a disciple of the Blessed One, having stayed there, having used up all the lifespan of those devas, is unbound right in that state of being. This, monks, is the difference, this the distinction, this the distinguishing factor, between an educated disciple of the noble ones and an uneducated run-of-the-mill person, when there is a destination, a reappearing.
              “These are four types of individuals to be found existing in the world.”`,
    source: "AN 4:125",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN4_125.html",
    category: "Goodwill",
  },
  {
    title: "Goodwill (2) / Mettā Sutta",
    content: `“Monks, there are these four types of individuals to be found existing in the world. Which four?
              “There is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with goodwill. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with goodwill: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “Again, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with compassion. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with compassion: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “Again, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with empathetic joy. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with empathetic joy: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “Again, there is the case where an individual keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with equanimity. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with equanimity: abundant, expansive, immeasurable, free from hostility, free from ill will. He regards whatever phenomena there that are connected with form, feeling, perception, fabrications, & consciousness, as inconstant, stressful, a disease, a cancer, an arrow, painful, an affliction, alien, a disintegration, an emptiness, not-self. At the break-up of the body, after death, he reappears in conjunction with the Devas of the Pure Abodes. This rebirth is not in common with run-of-the-mill people.
              “These are four types of individuals to be found existing in the world.”`,
    source: "AN 4:126",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN4_126.html",
    category: "Goodwill",
  },
  {
    title: "GoodWill / Mettā Sutta",
    content: `On one occasion the Blessed One was staying among the Koliyans. Now there is a Koliyan town named Haliddavasana. Then, early in the morning, a large number of monks adjusted their lower robes and, taking their bowls & outer robes, went into Haliddavasana for alms. Then the thought occurred to them, “It’s still too early to go for alms in Haliddavasana. Why don’t we go to the park of the wanderers of other sects?”
              So the monks went to the park of the wanderers of other sects. On arrival, they exchanged courteous greetings with the wanderers of other sects. After an exchange of friendly greetings & courtesies, they sat to one side.
              As they were sitting there, the wanderers of other sects said to them, “Friends, Gotama the contemplative teaches the Dhamma to his disciples in this way: ‘Come, monks. Abandoning the five hindrances, the corruptions of awareness that weaken discernment, keep pervading the first direction [the east] with an awareness imbued with goodwill, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with goodwill. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with compassion, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with compassion. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with empathetic joy, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with empathetic joy. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with equanimity, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with equanimity. Abundant, enlarged, immeasurable, without hostility, without ill will.’
              “Now, friends, we too teach our disciples in this way: ‘Come, you friends, abandoning the five hindrances, the corruptions of awareness that weaken discernment, keep pervading the first direction [the east] with an awareness imbued with goodwill, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with goodwill. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with compassion, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with compassion. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with empathetic joy, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with empathetic joy. Abundant, enlarged, immeasurable, without hostility, without ill will.
              “‘Keep pervading the first direction with an awareness imbued with equanimity, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, keep pervading the all-encompassing cosmos with an awareness imbued with equanimity. Abundant, enlarged, immeasurable, without hostility, without ill will.’
              “So, friends, what difference, what distinction, what distinguishing factor is there here between Gotama the contemplative and us, when comparing Dhamma teaching with Dhamma teaching, instruction with instruction?”
              Then the monks neither delighted in the words of the wanderers of other sects, nor did they reject them. Without delighting or rejecting, they got up from their seats and left, (thinking,) “We will learn the meaning of these words in the presence of the Blessed One.”
              So, having gone for alms in Haliddavasana, after the meal, returning from their alms round, the monks went to the Blessed One and, on arrival, having bowed down to him, sat to one side. As they were sitting there they [told him what had happened].
              “Monks, when wanderers of other sects speak in that way, they should be addressed in this way: ‘But how, friends, is awareness-release through goodwill developed, what is its destination, what is its excellence, its fruit, & its consummation? How is awareness-release through compassion developed, what is its destination, what is its excellence, its fruit, & its consummation? How is awareness-release through empathetic joy developed, what is its destination, what is its excellence, its fruit, & its consummation? How is awareness-release through equanimity developed, what is its destination, what is its excellence, its fruit, & its consummation?’
              “Being asked in this way, the wanderers of other sects will be unable to respond and, on top of that, will fall into vexation. Why is that? Because it lies beyond their range. Monks, I don’t see anyone in this cosmos with its devas, Māras, & Brahmās, in this generation with its contemplatives & brahmans, its royalty & commonfolk, who would satisfy the mind with their answer to these questions, aside from the Tathāgata, a disciple of the Tathāgata, or one who had heard it from them.
              “And how, monks, is awareness-release through goodwill developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by goodwill, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or he may enter & remain in the beautiful liberation. I tell you, monks, awareness-release through goodwill has the beautiful as its excellence, in the case of one who has penetrated to no higher release.
              “And how is awareness-release through compassion developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by compassion, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or, with the complete transcending of perceptions of (physical) form, with the disappearance of perceptions of resistance, and not attending to perceptions of multiplicity, (perceiving,) ‘Infinite space,’ he enters & remains in the sphere of the infinitude of space. I tell you, monks, awareness-release through compassion has the sphere of the infinitude of space as its excellence, in the case of one who has penetrated to no higher release.
              “And how is awareness-release through empathetic joy developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by empathetic joy, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or, with the complete transcending of the sphere of the infinitude of space, (perceiving,) ‘Infinite consciousness,’ he enters & remains in the sphere of the infinitude of consciousness. I tell you, monks, awareness-release through empathetic joy has the sphere of the infinitude of consciousness as its excellence, in the case of one who has penetrated to no higher release.
              “And how is awareness-release through equanimity developed, what is its destination, what is its excellence, its fruit, & its consummation?
              “There is the case where a monk develops mindfulness as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops analysis of qualities as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops persistence as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops rapture as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops calm as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops concentration as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. He develops equanimity as a factor for awakening accompanied by equanimity, dependent on seclusion, dependent on dispassion, dependent on cessation, resulting in letting go. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome. If he wants, he remains percipient of loathsomeness in the presence of what is not loathsome & what is. If he wants, he remains percipient of unloathsomeness in the presence of what is loathsome & what is not. If he wants, in the presence of what is loathsome & what is not, cutting himself off from both, he remains equanimous, alert, & mindful. Or, with the complete transcending of the sphere of the infinitude of consciousness, (perceiving,) ‘There is nothing,’ he enters & remains in the sphere of nothingness. I tell you, monks, awareness-release through equanimity has the sphere of nothingness as its excellence, in the case of one who has penetrated to no higher release. ”`,
    source: "SN 46:54",
    sourceUrl: "https://www.dhammatalks.org/suttas/SN/SN46_54.html",
    category: "Goodwill",
  },
  {
    title: "Means of Escape / Nissāraṇīya Sutta",
    content: `“Monks, these six properties are means of escape. Which six?
              “There is the case where a monk might say, ‘Although goodwill has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken by me as my awareness-release, still ill will keeps overpowering my mind.’ He should be told, ‘Don’t say that. You shouldn’t speak in that way. Don’t misrepresent the Blessed One, for it’s not right to misrepresent the Blessed One, and the Blessed One wouldn’t say that. It’s impossible, there is no way that, when goodwill has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken as an awareness-release, ill will would still keep overpowering the mind. That possibility doesn’t exist, for this is the escape from ill will: goodwill as an awareness-release.’
              “And further, there is the case where a monk might say, ‘Although compassion has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken by me as my awareness-release, still harmfulness keeps overpowering my mind.’ He should be told, ‘Don’t say that. You shouldn’t speak in that way. Don’t misrepresent the Blessed One, for it’s not right to misrepresent the Blessed One, and the Blessed One wouldn’t say that. It’s impossible, there is no way that, when compassion has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken as an awareness-release, harmfulness would still keep overpowering the mind. That possibility doesn’t exist, for this is the escape from harmfulness: compassion as an awareness-release.’
              “And further, there is the case where a monk might say, ‘Although empathetic joy has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken by me as my awareness-release, still resentment keeps overpowering my mind.’ He should be told, ‘Don’t say that. You shouldn’t speak in that way. Don’t misrepresent the Blessed One, for it’s not right to misrepresent the Blessed One, and the Blessed One wouldn’t say that. It’s impossible, there is no way that, when empathetic joy has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken as an awareness-release, resentment would still keep overpowering the mind. That possibility doesn’t exist, for this is the escape from resentment: empathetic joy as an awareness-release.’
              “And further, there is the case where a monk might say, ‘Although equanimity has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken by me as my awareness-release, still passion keeps overpowering my mind.’ He should be told, ‘Don’t say that. You shouldn’t speak in that way. Don’t misrepresent the Blessed One, for it’s not right to misrepresent the Blessed One, and the Blessed One wouldn’t say that. It’s impossible, there is no way that, when equanimity has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken as an awareness-release, passion would still keep overpowering the mind. That possibility doesn’t exist, for this is the escape from passion: equanimity as an awareness-release.’
              “And further, there is the case where a monk might say, ‘Although the signless has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken by me as my awareness-release, still my consciousness follows the drift of signs.’ He should be told, ‘Don’t say that. You shouldn’t speak in that way. Don’t misrepresent the Blessed One, for it’s not right to misrepresent the Blessed One, and the Blessed One wouldn’t say that. It’s impossible, there is no way that, when the signless has been developed, pursued, handed the reins, taken as a basis, steadied, consolidated, and well-undertaken as an awareness-release, consciousness would follow the drift of signs. That possibility doesn’t exist, for this is the escape from all signs: the signless as an awareness-release.’
              “And further, there is the case where a monk might say, ‘Although “I am” is gone, and I do not assume that “I am this,” still the arrow of uncertainty & perplexity keeps overpowering my mind.’ He should be told, ‘Don’t say that. You shouldn’t speak in that way. Don’t misrepresent the Blessed One, for it’s not right to misrepresent the Blessed One, and the Blessed One wouldn’t say that. It’s impossible, there is no way that, when “I am” is gone, and “I am this” is not assumed, the arrow of uncertainty & perplexity would keep overpowering the mind. That possibility doesn’t exist, for this is the escape from the arrow of uncertainty & perplexity: the uprooting of the conceit, “I am”.’
              “These, monks, are six properties that are means of escape.”`,
    source: "AN 6:13",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN6_13.html",
    category: "Unbinding",
  },
  {
    title: "Assemblies / Parisā Sutta",
    content: `“Monks, there are these three assemblies. Which three? The assembly of the supreme, the factional assembly, the harmonious assembly.
              “And which is the assembly of the supreme? There is the case where, in whatever assembly the elder monks are not lax or luxurious, have shunned the tossing away of their duties, have taken the lead in seclusion, and have aroused persistence for the attaining of the as-yet-unattained, the reaching of the as-yet-unreached, the realization of the as-yet-unrealized, the next generation follows their example. They, too, are not lax or luxurious. They shun the tossing away of their duties, they take the lead in seclusion, and they arouse persistence for the attaining of the as-yet-unattained, the reaching of the as-yet-unreached, the realization of the as-yet-unrealized. This is called the assembly of the supreme.
              “And which is the factional assembly? There is the case where, in whatever assembly the monks keep arguing, quarreling, & disputing, stabbing one another with weapons of the mouth, that is called the factional assembly.
              “And which is the harmonious assembly? There is the case where, in whatever assembly the monks dwell in harmony, on friendly terms, without quarreling, like milk mixed with water, viewing one another with eyes of affection, that is called the harmonious assembly.
              “Now, when the monks dwell in harmony, on friendly terms, without quarreling, like milk mixed with water, viewing one another with eyes of affection, at that time the monks produce much merit, at that time they dwell in a Brahmā dwelling, for example, empathetic joy as an awareness release. When one is joyful, rapture is born. In one who is enraptured at heart, the body grows calm. When the body is calm, one feels pleasure. Feeling pleasure, the mind becomes concentrated.
              “Just as when the devas pour rain in heavy drops on the upper mountains: The water, flowing down along the slopes, fills the branches of the mountain ravines & gullies. When the branches of the mountain ravines & gullies are full, they fill the little lakes. When the little lakes are full, they fill the large lakes… the little rivers… the large rivers. When the large rivers are full, they fill the ocean. In the same way, when the monks dwell in harmony, on friendly terms, without quarreling, like milk mixed with water, viewing one another with eyes of affection, at that time the monks produce much merit, at that time they dwell in a Brahmā dwelling, for example,, empathetic joy as an awareness release. When one is joyful, rapture is born. In one who is enraptured at heart, the body grows calm. When the body is calm, one feels pleasure. Feeling pleasure, the mind becomes concentrated.
              “These, monks, are the three assemblies.”`,
    source: "AN 3:96",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN3_96.html",
    category: "Sangha",
  },
  {
    title: "(Immeasurable) Concentration / Samādhi Sutta",
    content: `“Mindful & astute, you should develop immeasurable concentration [for example, concentration based on immeasurable goodwill, compassion, empathetic joy, or equanimity]. When, mindful & astute, one has developed immeasurable concentration, five realizations arise right within oneself. Which five?

              “The realization arises right within oneself that ‘This concentration is blissful in the present and will result in bliss in the future.’

              “The realization arises right within oneself that ‘This concentration is noble & not connected with the baits of the flesh.’

              “The realization arises right within oneself that ‘This concentration is not obtained by base people.’

              “The realization arises right within oneself that ‘This concentration is peaceful, exquisite, the acquiring of calm, the attainment of unification, not kept in place by the fabrications of forceful restraint.’

              “The realization arises right within oneself that ‘I enter into this concentration mindfully, and mindfully I emerge from it.’

              “Mindful & astute, you should develop immeasurable concentration. When, mindful & astute, one has developed immeasurable concentration, these five realizations arise right within oneself.”`,
    source: "AN 5:27",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN5_27.html",
    category: "Core Teachings",
  },
  {
    title: "The Conch Trumpet / Saṅkha Sutta",
    content: `On one occasion the Blessed One was staying near Nāḷandā in the Pāvārika Mango Grove. Then Asibandhakaputta the headman, a disciple of the Nigaṇṭhas, went to the Blessed One and on arrival, having bowed down to him, sat to one side. As he was sitting there the Blessed One said to him: “Headman, how does Nigaṇṭha Nāṭaputta teach the Dhamma to his disciples?”
              “Nigaṇṭha Nāṭaputta teaches the Dhamma to his disciples in this way, lord: ‘All those who take life are destined for a plane of deprivation, are destined for hell. All those who steal… All those who indulge in illicit sex… All those who tell lies are destined for a plane of deprivation, are destined for hell. Whatever one keeps doing frequently, by that is one led (to a state of rebirth).’ That’s how Nigaṇṭha Nāṭaputta teaches the Dhamma to his disciples.”
              “If it’s true that ‘Whatever one keeps doing frequently, by that is one led (to a state of rebirth),’ then no one is destined for a plane of deprivation or destined to hell in line with Nigaṇṭha Nāṭaputta’s words. What do you think, headman? If a man is one who takes life, then taking into consideration time spent doing & not doing, whether by day or by night, which time is more: the time he spends taking life or the time he spends not taking life?”
              “If a man is one who takes life, lord, then taking into consideration time spent doing & not doing, whether by day or by night, then the time he spends taking life is less, and the time he spends not taking life is certainly more. If it’s true that ‘Whatever one keeps doing frequently, by that is one led (to a state of rebirth),’ then no one is destined for a plane of deprivation or destined to hell in line with Nigaṇṭha Nāṭaputta’s words.”
              “What do you think, headman? If a man is one who steals… indulges in illicit sex… tells lies, then taking into consideration time spent doing & not doing, whether by day or by night, which time is more: the time he spends telling lies or the time he spends not telling lies?”
              “If a man is one who tells lies, lord, then taking into consideration time spent doing & not doing, whether by day or by night, then the time he spends telling lies is less, and the time he spends not telling lies is certainly more. If it’s true that ‘Whatever one keeps doing frequently, by that is one led (to a state of rebirth),’ then no one is destined for a plane of deprivation or destined to hell in line with Nigaṇṭha Nāṭaputta’s words.”
              “There’s the case, headman, where a certain teacher holds this doctrine, holds this view: ‘All those who take life are destined for a plane of deprivation, are destined for hell. All those who steal… All those who indulge in illicit sex… All those who tell lies are destined for a plane of deprivation, are destined for hell.’ A disciple has faith in that teacher, and the thought occurs to him, ‘Our teacher holds this doctrine, holds this view: “All those who take life are destined for a plane of deprivation, are destined for hell.” There are living beings that I have killed. I, too, am destined for a plane of deprivation, am destined for hell.’ He fastens onto that view. If he doesn’t abandon that doctrine, doesn’t abandon that state of mind, doesn’t relinquish that view, then as if he were to be carried off, he would thus be placed in hell.
              “(The thought occurs to him,) ‘Our teacher holds this doctrine, holds this view: ‘All those who steal… All those who indulge in illicit sex… All those who tell lies are destined for a plane of deprivation, are destined for hell.’ There are lies that I have told. I, too, am destined for a plane of deprivation, am destined for hell.’ He fastens onto that view. If he doesn’t abandon that doctrine, doesn’t abandon that state of mind, doesn’t relinquish that view, then as if he were to be carried off, he would thus be placed in hell.
              “There is the case, headman, where a Tathāgata appears in the world, worthy & rightly self-awakened, consummate in clear-knowing & conduct, well-gone, an expert with regard to the cosmos, unexcelled trainer of people fit to be tamed, teacher of devas & human beings, awakened, blessed. He, in various ways, criticizes & censures the taking of life, and says, ‘Abstain from taking life.’ He criticizes & censures stealing, and says, ‘Abstain from stealing.’ He criticizes & censures indulging in illicit sex, and says, ‘Abstain from indulging in illicit sex.’ He criticizes & censures the telling of lies, and says, ‘Abstain from the telling of lies.’
              “A disciple has faith in that teacher and reflects: ‘The Blessed One in a variety of ways criticizes & censures the taking of life, and says, “Abstain from taking life.” There are living beings that I have killed, to a greater or lesser extent. That was not right. That was not good. But if I become remorseful for that reason, that evil deed of mine will not be undone.’ So, reflecting thus, he abandons right then the taking of life, and in the future refrains from taking life. This is how there comes to be the abandoning of that evil deed. This is how there comes to be the transcending of that evil deed.
              “(He reflects:) ‘The Blessed One in a variety of ways criticizes & censures stealing… indulging in illicit sex… the telling of lies, and says, “Abstain from the telling of lies.” There are lies that I have told, to a greater or lesser extent. That was not right. That was not good. But if I become remorseful for that reason, that evil deed of mine will not be undone.’ So, reflecting thus, he abandons right then the telling of lies, and in the future refrains from telling lies. This is how there comes to be the abandoning of that evil deed. This is how there comes to be the transcending of that evil deed.
              “Having abandoned the taking of life, he refrains from taking life. Having abandoned stealing, he refrains from stealing. Having abandoned illicit sex, he refrains from illicit sex. Having abandoned lies, he refrains from lies. Having abandoned divisive speech, he refrains from divisive speech. Having abandoned harsh speech, he refrains from harsh speech. Having abandoned idle chatter, he refrains from idle chatter. Having abandoned covetousness, he becomes uncovetous. Having abandoned ill will & anger, he becomes one with a mind of no ill will. Having abandoned wrong views, he becomes one who has right views.
              “That disciple of the noble ones, headman, thus devoid of covetousness, devoid of ill will, unbewildered, alert, mindful, keeps pervading the first direction [the east] with an awareness imbued with goodwill, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, he keeps pervading the all-encompassing cosmos with an awareness imbued with goodwill, abundant, enlarged, immeasurable, without hostility, without ill will. Just as a strong conch-trumpet blower can notify the four directions without any difficulty, in the same way, when the awareness-release through goodwill is thus developed, thus pursued, any deed done to a limited extent no longer remains there, no longer stays there.
              “That disciple of the noble ones, thus devoid of covetousness, devoid of ill will, unbewildered, alert, mindful, keeps pervading the first direction with an awareness imbued with compassion… empathetic joy… equanimity, likewise the second, likewise the third, likewise the fourth. Thus above, below, & all around, everywhere, in its entirety, he keeps pervading the all-encompassing cosmos with an awareness imbued with equanimity, abundant, enlarged, immeasurable, without hostility, without ill will. Just as a strong conch-trumpet blower can notify the four directions without any difficulty, in the same way, when the awareness-release through equanimity is thus developed, thus pursued, any deed done to a limited extent no longer remains there, no longer stays there.”
              When this was said, Asibandhakaputta the headman, the disciple of the Nigaṇṭhas, said to the Blessed One: “Magnificent, lord! Magnificent! Just as if he were to place upright what was overturned, to reveal what was hidden, to show the way to one who was lost, or to carry a lamp into the dark so that those with eyes could see forms, in the same way has the Blessed One, through many lines of reasoning—made the Dhamma clear. I go to the Blessed One for refuge, to the Dhamma, & to the Saṅgha of monks. May the Blessed One remember me as a lay follower who has gone for refuge from this day forward, for life.”`,
    source: "SN 42:8",
    sourceUrl: "https://www.dhammatalks.org/suttas/SN/SN42_8.html",
    category: "Meditation",
  },
  {
    title: "The Greater Exhortation to Rāhula / Mahā Rāhulovāda Sutta",
    content: `I have heard that on one occasion the Blessed One was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. Then the Blessed One, early in the morning, adjusted his lower robe and, taking his bowl & outer robe, went into Sāvatthī for alms. And Venerable Rāhula, early in the morning, adjusted his lower robe and, taking his bowl & outer robe, went into Sāvatthī for alms following right behind the Blessed One. Then the Blessed One, looking back at Rāhula, addressed him: “Rāhula, any form whatsoever that is past, future, or present; internal or external; blatant or subtle; common or sublime; far or near: Every form is to be seen as it has come to be with right discernment as: ‘This is not mine. This is not my self. This is not what I am.’”
              “Just form, O Blessed One? Just form, O One Well-Gone?”
              “Form, Rāhula, & feeling & perception & fabrications & consciousness.”
              Then the thought occurred to Venerable Rāhula, “Who, having been exhorted face-to-face by the Blessed One, would go into the town for alms today?” So he turned back and sat down at the foot of a tree, folding his legs crosswise, holding his body erect, & establishing mindfulness to the fore.
              Venerable Sāriputta saw Venerable Rāhula sitting at the foot of a tree, his legs folded crosswise, his body held erect, & with mindfulness set to the fore. On seeing him, he said to him, “Rāhula, develop the meditation [bhāvanā] of mindfulness of in-&-out breathing. The meditation of mindfulness of in-&-out breathing, when developed & pursued, is of great fruit, of great benefit.”
              Then Venerable Rāhula, emerging from his seclusion in the evening, went to the Blessed One and, having bowed down to him, sat to one side. As he was sitting there he said to the Blessed One, “How, lord, is mindfulness of in-&-out breathing to be developed & pursued so as to be of great fruit, or great benefit?”
              “Rāhula, any form whatsoever that is past, future, or present; internal or external; blatant or subtle; common or sublime; far or near: Every form is to be seen as it has come to be with right discernment as: ‘This is not mine. This is not my self. This is not what I am.’ There are these five properties, Rāhula. Which five? The earth property, the water property, the fire property, the wind property, & the space property.
              “And what is the earth property? The earth property may be either internal or external. What is the internal earth property? Anything internal, within oneself, that’s hard, solid, & sustained (by craving): head hairs, body hairs, nails, teeth, skin, flesh, tendons, bones, bone marrow, kidneys, heart, liver, membranes, spleen, lungs, large intestines, small intestines, contents of the stomach, feces, or anything else internal, within oneself, that’s hard, solid, and sustained: This is called the internal earth property. Now both the internal earth property & the external earth property are simply earth property. And that should be seen as it has come to be with right discernment: ‘This is not mine, this is not what I am, this is not my self.’ When one sees it thus as it has come to be with right discernment, one becomes disenchanted with the earth property and makes the earth property fade from the mind.
              “And what is the water property? The water property may be either internal or external. What is the internal water property? Anything internal, within oneself, that’s water, watery, & sustained: bile, phlegm, pus, blood, sweat, fat, tears, oil, saliva, mucus, oil-of-the-joints, urine, or anything else internal, within oneself, that’s water, watery, & sustained: This is called the internal water property. Now both the internal water property & the external water property are simply water property. And that should be seen as it has come to be with right discernment: ‘This is not mine, this is not what I am, this is not my self.’ When one sees it thus as it has come to be with right discernment, one becomes disenchanted with the water property and makes the water property fade from the mind.
              “And what is the fire property? The fire property may be either internal or external. What is the internal fire property? Anything internal, within oneself, that’s fire, fiery, & sustained: that by which (the body) is warmed, aged, & consumed with fever; and that by which what is eaten, drunk, chewed, & savored gets properly digested; or anything else internal, within oneself, that’s fire, fiery, & sustained: This is called the internal fire property. Now both the internal fire property & the external fire property are simply fire property. And that should be seen as it has come to be with right discernment: ‘This is not mine, this is not what I am, this is not my self.’ When one sees it thus as it has come to be with right discernment, one becomes disenchanted with the fire property and makes the fire property fade from the mind.
              “And what is the wind property? The wind property may be either internal or external. What is the internal wind property? Anything internal, within oneself, that’s wind, windy, & sustained: up-going winds, down-going winds, winds in the stomach, winds in the intestines, winds that course through the body, in-and-out breathing, or anything else internal, within oneself, that’s wind, windy, & sustained: This is called the internal wind property. Now both the internal wind property & the external wind property are simply wind property. And that should be seen as it has come to be with right discernment: ‘This is not mine, this is not what I am, this is not my self.’ When one sees it thus as it has come to be with right discernment, one becomes disenchanted with the wind property and makes the wind property fade from the mind.
              “And what is the space property? The space property may be either internal or external. What is the internal space property? Anything internal, within oneself, that’s space, spatial, & sustained: the holes of the ears, the nostrils, the mouth, the (passage) whereby what is eaten, drunk, consumed, & tasted gets swallowed, and where it collects, and whereby it is excreted from below, or anything else internal, within oneself, that’s space, spatial, & sustained: This is called the internal space property. Now both the internal space property & the external space property are simply space property. And that should be seen as it has come to be with right discernment: ‘This is not mine, this is not what I am, this is not my self.’ When one sees it thus as it has come to be with right discernment, one becomes disenchanted with the space property and makes the space property fade from the mind.
              “Rāhula, develop the meditation in tune with earth. For when you are developing the meditation in tune with earth, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind. Just as when people throw what is clean or unclean on the earth, feces, urine, saliva, pus, or blood, the earth is not horrified, humiliated, or disgusted by it; in the same way, when you are developing the meditation in tune with earth, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind.
              “Develop the meditation in tune with water. For when you are developing the meditation in tune with water, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind. Just as when people wash what is clean or unclean in water, feces, urine, saliva, pus, or blood, the water is not horrified, humiliated, or disgusted by it; in the same way, when you are developing the meditation in tune with water, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind.
              “Develop the meditation in tune with fire. For when you are developing the meditation in tune with fire, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind. Just as when fire burns what is clean or unclean, feces, urine, saliva, pus, or blood, it is not horrified, humiliated, or disgusted by it; in the same way, when you are developing the meditation in tune with fire, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind.
              “Develop the meditation in tune with wind. For when you are developing the meditation in tune with wind, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind. Just as when wind blows what is clean or unclean, feces, urine, saliva, pus, or blood, it is not horrified, humiliated, or disgusted by it; in the same way, when you are developing the meditation in tune with wind, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind.
              “Develop the meditation in tune with space. For when you are developing the meditation in tune with space, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind. Just as space is not established anywhere, in the same way, when you are developing the meditation in tune with space, agreeable & disagreeable sensory impressions that have arisen will not stay in charge of your mind.
              “Develop the meditation of goodwill. For when you are developing the meditation of goodwill, ill-will will be abandoned.
              “Develop the meditation of compassion. For when you are developing the meditation of compassion, harmfulness will be abandoned.
              “Develop the meditation of empathetic joy. For when you are developing the meditation of empathetic joy, resentment will be abandoned.
              “Develop the meditation of equanimity. For when you are developing the meditation of equanimity, irritation will be abandoned.
              “Develop the meditation of the unattractive. For when you are developing the meditation of the unattractive, passion will be abandoned.
              “Develop the meditation of the perception of inconstancy. For when you are developing the meditation of the perception of inconstancy, the conceit ‘I am’ will be abandoned.
              “Develop the meditation of mindfulness of in-&-out breathing. Mindfulness of in-&-out breathing, when developed & pursued, is of great fruit, of great benefit.
              “And how, Rāhula, is mindfulness of in-&-out breathing developed & pursued so as to be of great fruit, of great benefit?
              “There is the case where a monk, having gone to the wilderness, to the shade of a tree, or to an empty building, sits down folding his legs crosswise, holding his body erect, and establishing mindfulness to the fore. Always mindful, he breathes in; mindful he breathes out.
              “Breathing in long, he discerns, ‘I am breathing in long’; or breathing out long, he discerns, ‘I am breathing out long.’  Or breathing in short, he discerns, ‘I am breathing in short’; or breathing out short, he discerns, ‘I am breathing out short.’  He trains himself, ‘I will breathe in sensitive to the entire body.’ He trains himself, ‘I will breathe out sensitive to the entire body.’ He trains himself, ‘I will breathe in calming bodily fabrication.’ He trains himself, ‘I will breathe out calming bodily fabrication.’
              “He trains himself, ‘I will breathe in sensitive to rapture.’ He trains himself, ‘I will breathe out sensitive to rapture.’ He trains himself, ‘I will breathe in sensitive to pleasure.’ He trains himself, ‘I will breathe out sensitive to pleasure.’ He trains himself, ‘I will breathe in sensitive to mental fabrication.’ He trains himself, ‘I will breathe out sensitive to mental fabrication.’ He trains himself, ‘I will breathe in calming mental fabrication.’ He trains himself, ‘I will breathe out calming mental fabrication.’
              “He trains himself, ‘I will breathe in sensitive to the mind.’ He trains himself, ‘I will breathe out sensitive to the mind.’  He trains himself, ‘I will breathe in satisfying the mind.’ He trains himself, ‘I will breathe out satisfying the mind.’  He trains himself, ‘I will breathe in concentrating the mind.’ He trains himself, ‘I will breathe out concentrating the mind. He trains himself, ‘I will breathe in releasing the mind.’ He trains himself, ‘I will breathe out releasing the mind.’
              “He trains himself, ‘I will breathe in focusing on inconstancy.’ He trains himself, ‘I will breathe out focusing on inconstancy.’  He trains himself, ‘I will breathe in focusing on dispassion [lit: fading].’ He trains himself, ‘I will breathe out focusing on dispassion.’  He trains himself, ‘I will breathe in focusing on cessation.’ He trains himself, ‘I will breathe out focusing on cessation.’  He trains himself, ‘I will breathe in focusing on relinquishment.’ He trains himself, ‘I will breathe out focusing on relinquishment.’
              “This, Rāhula, is how mindfulness of in-&-out breathing is developed & pursued so as to be of great fruit, of great benefit.
              “When mindfulness of in-&-out breathing is developed & pursued in this way, even one’s final in-breaths & out-breaths are known as they cease, not unknown.”
              That is what the Blessed One said. Gratified, Venerable Rāhula delighted in the Blessed One’s words.`,
    source: "MN 62",
    sourceUrl: "https://www.dhammatalks.org/suttas/MN/MN62.html",
    category: "Rahula",
  },
  {
    title: "To the Kālāmas / Kālāma Sutta",
    content: `I have heard that on one occasion the Blessed One, on a wandering tour among the Kosalans with a large Saṅgha of monks, arrived at Kesaputta, a town of the Kālāmas. The Kālāmas of Kesaputta heard it said, “Gotama the contemplative, the son of the Sakyans, having gone forth from the Sakyan clan, has arrived at Kesaputta. And of that Master Gotama this fine reputation has spread: ‘He is indeed a Blessed One, worthy & rightly self-awakened, consummate in clear-knowing & conduct, Well-Gone, an expert with regard to the cosmos, unexcelled trainer of people fit to be tamed, teacher of devas & human beings, awakened, blessed. He makes known, having realized it through direct knowledge, this world with its devas, Māras, & Brahmās, this generation with its contemplatives & brahmans, its royalty & commonfolk; he explains the Dhamma admirable in the beginning, admirable in the middle, admirable in the end; he expounds the holy life both in its particulars & in its essence, entirely perfect, surpassingly pure. It is good to see such a worthy one.’”
              So the Kālāmas of Kesaputta went to the Blessed One. On arrival, some of them bowed down to the Blessed One and sat to one side. Some of them exchanged courteous greetings with him and, after an exchange of friendly greetings & courtesies, sat to one side. Some of them sat to one side having saluted him with their hands palm-to-palm over their hearts. Some of them sat to one side having announced their name & clan. Some of them sat to one side in silence.
              As they were sitting there, the Kālāmas of Kesaputta said to the Blessed One, “Lord, there are some contemplatives & brahmans who come to Kesaputta. They expound & glorify their own doctrines, but as for the doctrines of others, they deprecate them, disparage them, show contempt for them, & pull them to pieces. And then other contemplatives & brahmans come to Kesaputta. They expound & glorify their own doctrines, but as for the doctrines of others, they deprecate them, disparage them, show contempt for them, & pull them to pieces. They leave us absolutely uncertain & in doubt: Which of these venerable contemplatives & brahmans are speaking the truth, and which ones are lying?”
              “Of course you are uncertain, Kālāmas. Of course you are in doubt. When there are reasons for doubt, uncertainty is born. So in this case, Kālāmas, don’t go by reports, by legends, by traditions, by scripture, by logical conjecture, by inference, by analogies, by agreement through pondering views, by probability, or by the thought, ‘This contemplative is our teacher.’ When you know for yourselves that, ‘These qualities are unskillful; these qualities are blameworthy; these qualities are criticized by the observant; these qualities, when adopted & carried out, lead to harm & to suffering’, then you should abandon them.
              “What do you think, Kālāmas? When greed arises in a person, does it arise for welfare or for harm?”
              “For harm, lord.”
              “And this greedy person, overcome by greed, his mind possessed by greed, kills living beings, takes what is not given, goes after another person’s wife, tells lies, and induces others to do likewise, all of which is for long-term harm & suffering.”
              “Yes, lord.”
              “Now, what do you think, Kālāmas? When aversion arises in a person, does it arise for welfare or for harm?”
              “For harm, lord.”
              “And this aversive person, overcome by aversion, his mind possessed by aversion, kills living beings, takes what is not given, goes after another person’s wife, tells lies, and induces others to do likewise, all of which is for long-term harm & suffering.”
              “Yes, lord.”
              “Now, what do you think, Kālāmas? When delusion arises in a person, does it arise for welfare or for harm?”
              “For harm, lord.”
              “And this deluded person, overcome by delusion, his mind possessed by delusion, kills living beings, takes what is not given, goes after another person’s wife, tells lies, and induces others to do likewise, all of which is for long-term harm & suffering.”
              “Yes, lord.”
              “So what do you think, Kālāmas: Are these qualities skillful or unskillful?”
              “Unskillful, lord.”
              “Blameworthy or blameless?”
              “Blameworthy, lord.”
              “Criticized by the observant or praised by the observant?”
              “Criticized by the observant, lord.”
              “When adopted & carried out, do they lead to harm & to suffering, or not?”
              “When adopted & carried out, they lead to harm & to suffering. That is how it appears to us.”
              “So, as I said, Kālāmas: ‘Don’t go by reports, by legends, by traditions, by scripture, by logical conjecture, by inference, by analogies, by agreement through pondering views, by probability, or by the thought, “This contemplative is our teacher.” When you know for yourselves that, “These qualities are unskillful; these qualities are blameworthy; these qualities are criticized by the observant; these qualities, when adopted & carried out, lead to harm & to suffering”, then you should abandon them.’ Thus was it said. And in reference to this was it said.
              “Now, Kālāmas, don’t go by reports, by legends, by traditions, by scripture, by logical conjecture, by inference, by analogies, by agreement through pondering views, by probability, or by the thought, ‘This contemplative is our teacher.’ When you know for yourselves that, ‘These qualities are skillful; these qualities are blameless; these qualities are praised by the observant; these qualities, when adopted & carried out, lead to welfare & to happiness’, then you should enter & remain in them.
              “What do you think, Kālāmas? When lack of greed arises in a person, does it arise for welfare or for harm?”
              “For welfare, lord.”
              “And this ungreedy person, not overcome by greed, his mind not possessed by greed, doesn’t kill living beings, take what is not given, go after another person’s wife, tell lies, or induce others to do likewise, all of which is for long-term welfare & happiness.”
              “Yes, lord.”
              “What do you think, Kālāmas? When lack of aversion arises in a person, does it arise for welfare or for harm?”
              “For welfare, lord.”
              “And this unaversive person, not overcome by aversion, his mind not possessed by aversion, doesn’t kill living beings, take what is not given, go after another person’s wife, tell lies, or induce others to do likewise, all of which is for long-term welfare & happiness.”
              “Yes, lord.”
              “What do you think, Kālāmas? When lack of delusion arises in a person, does it arise for welfare or for harm?”
              “For welfare, lord.”
              “And this undeluded person, not overcome by delusion, his mind not possessed by delusion, doesn’t kill living beings, take what is not given, go after another person’s wife, tell lies, or induce others to do likewise, all of which is for long-term welfare & happiness.”
              “Yes, lord.”
              “So what do you think, Kālāmas: Are these qualities skillful or unskillful?”
              “Skillful, lord.”
              “Blameworthy or blameless?”
              “Blameless, lord.”
              “Criticized by the observant or praised by the observant?”
              “Praised by the observant, lord.”
              “When adopted & carried out, do they lead to welfare & to happiness, or not?”
              “When adopted & carried out, they lead to welfare & to happiness. That is how it appears to us.”
              “So, as I said, Kālāmas: ‘Don’t go by reports, by legends, by traditions, by scripture, by logical conjecture, by inference, by analogies, by agreement through pondering views, by probability, or by the thought, “This contemplative is our teacher.” When you know for yourselves that, “These qualities are skillful; these qualities are blameless; these qualities are praised by the observant; these qualities, when adopted & carried out, lead to welfare & to happiness”, then you should enter & remain in them.’ Thus was it said. And in reference to this was it said.
              “Now, Kālāmas, one who is a disciple of the noble ones, thus devoid of greed, devoid of ill will, undeluded, alert, & resolute, keeps pervading the first direction [the east], as well as the second direction, the third, & the fourth, with an awareness imbued with goodwill. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with goodwill: abundant, expansive, immeasurable, free from hostility, free from ill will.
              “He keeps pervading the first direction, as well as the second direction, the third, & the fourth, with an awareness imbued with compassion. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with compassion: abundant, expansive, immeasurable, free from hostility, free from ill will.
              “He keeps pervading the first direction, as well as the second direction, the third, & the fourth, with an awareness imbued with empathetic joy. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with empathetic joy: abundant, expansive, immeasurable, free from hostility, free from ill will.
              “He keeps pervading the first direction, as well as the second direction, the third, & the fourth, with an awareness imbued with equanimity. Thus he keeps pervading above, below, & all around, everywhere & in every respect the all-encompassing cosmos with an awareness imbued with equanimity: abundant, expansive, immeasurable, free from hostility, free from ill will.
              “Now, Kālāmas, one who is a disciple of the noble ones, his mind thus free from hostility, free from ill will, undefiled, & pure, acquires four assurances in the here & now:
              “‘If there is a world after death, if there is the fruit & result of actions rightly & wrongly done, then this is the basis by which, with the break-up of the body, after death, I will reappear in a good destination, a heavenly world.’ This is the first assurance he acquires.
              “‘But if there is no world after death, if there is no fruit & result of actions rightly & wrongly done, then here in the present life I look after myself with ease, free from hostility, free from ill will, free from trouble.’ This is the second assurance he acquires.
              “‘If evil is done through acting, still I have willed no evil for anyone. Having done no evil action, from where will suffering touch me?’ This is the third assurance he acquires.
              “‘But if no evil is done through acting, then I can assume myself pure in both respects.’ This is the fourth assurance he acquires.
              “One who is a disciple of the noble ones, his mind thus free from hostility, free from ill will, undefiled, & pure, acquires these four assurances in the here & now.”
              “So it is, Blessed One. So it is, O One Well-Gone. One who is a disciple of the noble ones, his mind thus free from hostility, free from ill will, undefiled, & pure, acquires four assurances in the here & now:
              “‘If there is a world after death, if there is the fruit & result of actions rightly & wrongly done, then this is the basis by which, with the break-up of the body, after death, I will reappear in a good destination, a heavenly world.’ This is the first assurance he acquires.
              “‘But if there is no world after death, if there is no fruit & result of actions rightly & wrongly done, then here in the present life I look after myself with ease, free from hostility, free from ill will, free from trouble.’ This is the second assurance he acquires.
              “‘If evil is done through acting, still I have willed no evil for anyone. Having done no evil action, from where will suffering touch me?’ This is the third assurance he acquires.
              “‘But if no evil is done through acting, then I can assume myself pure in both ways.’ This is the fourth assurance he acquires.
              “One who is a disciple of the noble ones, his mind thus free from hostility, free from ill will, undefiled, & pure, acquires these four assurances in the here & now.
              “Magnificent, lord! Magnificent! Just as if he were to place upright what was overturned, to reveal what was hidden, to show the way to one who was lost, or to carry a lamp into the dark so that those with eyes could see forms, in the same way has the Blessed One, through many lines of reasoning, made the Dhamma clear. We go to the Blessed One for refuge, to the Dhamma, and to the Saṅgha of monks. May the Blessed One remember us as lay followers who have gone to him for refuge, from this day forward, for life.”`,
    source: "AN 3:66",
    sourceUrl: "https://www.dhammatalks.org/suttas/AN/AN3_66.html",
    category: "Core Teachings",
  },
  {
    title: "Food (for the Factors for awakening) / Āhāra Sutta",
    content: `“Monks, I will teach you the feeding & starving of the five hindrances & of the seven factors for awakening. Listen & pay close attention. I will speak.…
              Feeding the hindrances
              “And what is the food for the arising of unarisen sensual desire, or for the growth & increase of sensual desire once it has arisen? There is the theme of beauty. To foster inappropriate attention to it: This is the food for the arising of unarisen sensual desire, or for the growth & increase of sensual desire once it has arisen.
              “And what is the food for the arising of unarisen ill will, or for the growth & increase of ill will once it has arisen? There is the theme of irritation. To foster inappropriate attention to it: This is the food for the arising of unarisen ill will, or for the growth & increase of ill will once it has arisen.
              “And what is the food for the arising of unarisen sloth & drowsiness, or for the growth & increase of sloth & drowsiness once it has arisen? There are boredom, weariness, yawning, drowsiness after a meal, & sluggishness of awareness. To foster inappropriate attention to them: This is the food for the arising of unarisen sloth & drowsiness, or for the growth & increase of sloth & drowsiness once it has arisen.
              “And what is the food for the arising of unarisen restlessness & anxiety, or for the growth & increase of restlessness & anxiety once it has arisen? There is non-stillness of awareness. To foster inappropriate attention to that: This is the food for the arising of unarisen restlessness & anxiety, or for the growth & increase of restlessness & anxiety once it has arisen.
              “And what is the food for the arising of unarisen uncertainty, or for the growth & increase of uncertainty once it has arisen? There are phenomena that act as a foothold for uncertainty. To foster inappropriate attention to them: This is the food for the arising of unarisen uncertainty, or for the growth & increase of uncertainty once it has arisen.
              Feeding the factors for awakening
              “Now, what is the food for the arising of unarisen mindfulness as a factor for awakening, or for the growth & increase of mindfulness as a factor for awakening once it has arisen? There are mental qualities that act as a foothold for mindfulness as a factor for awakening [well-purified virtue & views made straight]. To foster appropriate attention to them: This is the food for the arising of unarisen mindfulness as a factor for awakening, or for the growth & increase of mindfulness as a factor for awakening once it has arisen.
              “And what is the food for the arising of unarisen analysis of qualities as a factor for awakening, or for the growth & increase of analysis of qualities… once it has arisen? There are mental qualities that are skillful & unskillful, blameworthy & blameless, gross & refined, siding with darkness & with light. To foster appropriate attention to them: This is the food for the arising of unarisen analysis of qualities as a factor for awakening, or for the growth & increase of analysis of qualities… once it has arisen.
              “And what is the food for the arising of unarisen persistence as a factor for awakening, or for the growth & increase of persistence… once it has arisen? There is the potential for effort, the potential for exertion, the potential for striving. To foster appropriate attention to them: This is the food for the arising of unarisen persistence as a factor for awakening, or for the growth & increase of persistence… once it has arisen.
              “And what is the food for the arising of unarisen rapture as a factor for awakening, or for the growth & increase of rapture… once it has arisen? There are mental qualities that act as a foothold for rapture as a factor for awakening. To foster appropriate attention to them: This is the food for the arising of unarisen rapture as a factor for awakening, or for the growth & increase of rapture… once it has arisen.
              “And what is the food for the arising of unarisen calm as a factor for awakening, or for the growth & increase of calm… once it has arisen? There is physical calm & there is mental calm. To foster appropriate attention to them: This is the food for the arising of unarisen calm as a factor for awakening, or for the growth & increase of calm… once it has arisen.
              “And what is the food for the arising of unarisen concentration as a factor for awakening, or for the growth & increase of concentration… once it has arisen? There are themes for tranquility, themes for non-distraction [these are the four establishings of mindfulness]. To foster appropriate attention to them: This is the food for the arising of unarisen concentration as a factor for awakening, or for the growth & increase of concentration… once it has arisen.
              “And what is the food for the arising of unarisen equanimity as a factor for awakening, or for the growth & increase of equanimity… once it has arisen? There are mental qualities that act as a foothold for equanimity as a factor for awakening. To foster appropriate attention to them: This is the food for the arising of unarisen equanimity as a factor for awakening, or for the growth & increase of equanimity as a factor for awakening once it has arisen.
              Starving the hindrances
              “Now, what is lack of food for the arising of unarisen sensual desire, or for the growth & increase of sensual desire once it has arisen? There is the theme of unattractiveness. To foster appropriate attention to it: This is lack of food for the arising of unarisen sensual desire, or for the growth & increase of sensual desire once it has arisen.
              “And what is lack of food for the arising of unarisen ill will, or for the growth & increase of ill will once it has arisen? There is awareness-release [through goodwill, compassion, empathetic joy, or equanimity]. To foster appropriate attention to that: This is lack of food for the arising of unarisen ill will, or for the growth & increase of ill will once it has arisen.
              “And what is lack of food for the arising of unarisen sloth & drowsiness, or for the growth & increase of sloth & drowsiness once it has arisen? There is the potential for effort, the potential for exertion, the potential for striving. To foster appropriate attention to them: This is lack of food for the arising of unarisen sloth & drowsiness, or for the growth & increase of sloth & drowsiness once it has arisen.
              “And what is lack of food for the arising of unarisen restlessness & anxiety, or for the growth & increase of restlessness & anxiety once it has arisen? There is stillness of awareness. To foster appropriate attention to that: This is lack of food for the arising of unarisen restlessness & anxiety, or for the growth & increase of restlessness & anxiety once it has arisen.
              “And what is lack of food for the arising of unarisen uncertainty, or for the growth & increase of uncertainty once it has arisen? There are mental qualities that are skillful & unskillful, blameworthy & blameless, gross & refined, siding with darkness & with light. To foster appropriate attention to them: This is lack of food for the arising of unarisen uncertainty, or for the growth & increase of uncertainty once it has arisen.
              Starving the factors for awakening
              “Now, what is lack of food for the arising of unarisen mindfulness as a factor for awakening, or for the growth & increase of mindfulness as a factor for awakening once it has arisen? There are mental qualities that act as a foothold for mindfulness as a factor for awakening. Not fostering attention to them: This is lack of food for the arising of unarisen mindfulness as a factor for awakening, or for the growth & increase of mindfulness as a factor for awakening once it has arisen.
              “And what is lack of food for the arising of unarisen analysis of qualities as a factor for awakening, or for the growth & increase of analysis of qualities… once it has arisen? There are mental qualities that are skillful & unskillful, blameworthy & blameless, gross & refined, siding with darkness & with light. Not fostering attention to them: This is lack of food for the arising of unarisen analysis of qualities as a factor for awakening, or for the growth & increase of analysis of qualities… once it has arisen.
              “And what is lack of food for the arising of unarisen persistence as a factor for awakening, or for the growth & increase of persistence… once it has arisen? There is the potential for effort, the potential for exertion, the potential for striving. Not fostering attention to them: This is lack of food for the arising of unarisen persistence as a factor for awakening, or for the growth & increase of persistence… once it has arisen.
              “And what is lack of food for the arising of unarisen rapture as a factor for awakening, or for the growth & increase of rapture… once it has arisen? There are mental qualities that act as a foothold for rapture as a factor for awakening. Not fostering attention to them: This is lack of food for the arising of unarisen rapture as a factor for awakening, or for the growth & increase of rapture… once it has arisen.
              “And what is lack of food for the arising of unarisen calm as a factor for awakening, or for the growth & increase of calm… once it has arisen? There is physical calm & there is mental calm. Not fostering attention to them: This is lack of food for the arising of unarisen calm as a factor for awakening, or for the growth & increase of calm… once it has arisen.
              “And what is lack of food for the arising of unarisen concentration as a factor for awakening, or for the growth & increase of concentration… once it has arisen? There are the themes for tranquility, themes for non-distraction. Not fostering attention to them: This is lack of food for the arising of unarisen concentration as a factor for awakening, or for the growth & increase of concentration… once it has arisen.
              “And what is lack of food for the arising of unarisen equanimity as a factor for awakening, or for the growth & increase of equanimity as a factor for awakening once it has arisen? There are mental qualities that act as a foothold for equanimity as a factor for awakening. Not fostering attention to them: This is lack of food for the arising of unarisen equanimity as a factor for awakening, or for the growth & increase of equanimity as a factor for awakening once it has arisen.”`,
    source: "SN 46:51",
    sourceUrl: "https://www.dhammatalks.org/suttas/SN/SN46_51.html",
    category: "Meditation",
  },
  {
    title: "The Shorter Set of Questions & Answers / Cūḷa Vedalla Sutta",
    content: `I have heard that on one occasion the Blessed One was staying near Rājagaha in the Bamboo Forest, the Squirrels’ Sanctuary. Then Visākha the lay follower went to Dhammadinnā the nun and, on arrival, having bowed down to her, sat to one side.
              Self-identification:
              As he was sitting there he said to her, “‘Self-identification, self-identification,’ it is said, lady. Which self-identification is described by the Blessed One?”
              “There are these five clinging-aggregates, friend Visākha: the form clinging-aggregate, the feeling clinging-aggregate, the perception clinging-aggregate, the fabrications clinging-aggregate, the consciousness clinging-aggregate. These five clinging-aggregates are the self-identification described by the Blessed One.”
              Saying, “Yes, lady,” Visākha the lay follower delighted & rejoiced in what Dhammadinnā the nun had said. Then he asked her a further question: “‘The origination of self-identification, the origination of self-identification,’ it is said, lady. Which origination of self-identification is described by the Blessed One?”
              “The craving that makes for further becoming, accompanied by passion & delight, relishing now here & now there, for example,, craving for sensual pleasure, craving for becoming, craving for non-becoming: This, friend Visākha, is the origination of self-identification described by the Blessed One.”
              “‘The cessation of self-identification, the cessation of self-identification,’ it is said, lady. Which cessation of self-identification is described by the Blessed One?”
              “The remainderless fading & cessation, renunciation, relinquishment, release, & letting go of that very craving: This, friend Visākha, is the cessation of self-identification described by the Blessed One.”
              “‘The way of practice leading to the cessation of self-identification, the way of practice leading to the cessation of self-identification,’ it is said, lady. Which way of practice leading to the cessation of self-identification is described by the Blessed One?”
              “Precisely this noble eightfold path, right view, right resolve, right speech, right action, right livelihood, right effort, right mindfulness, right concentration: This, friend Visākha, is the way of practice leading to the cessation of self-identification described by the Blessed One.”
              “Is it the case, lady, that clinging is the same thing as the five clinging-aggregates or is it something separate?”
              “Friend Visākha, neither is clinging the same thing as the five clinging-aggregates, nor is it something separate. Whatever desire & passion there is with regard to the five clinging-aggregates, that is the clinging there.”
              “But, lady, how does self-identification view come about?”
              “There is the case, friend Visākha, where an uninstructed run-of-the-mill person, who has no regard for noble ones, is not well-versed or disciplined in their Dhamma; who has no regard for people of integrity, is not well-versed or disciplined in their Dhamma, assumes form [e.g., the body] to be the self, or the self as possessing form, or form as in the self, or the self as in form.
              “He assumes feeling to be the self.…
              “He assumes perception to be the self.…
              “He assumes fabrications to be the self.…
              “He assumes consciousness to be the self, or the self as possessing consciousness, or consciousness as in the self, or the self as in consciousness. This is how self-identification view comes about.”
              “But, lady, how does self-identification view not come about?”
              “There is the case where a well-instructed disciple of the noble ones, who has regard for noble ones, is well-versed & disciplined in their Dhamma; who has regard for people of integrity, is well-versed & disciplined in their Dhamma,  doesn’t assume form to be the self, or the self as possessing form, or form as in the self, or the self as in form.
              “He doesn’t assume feeling to be the self.…
              “He doesn’t assume perception to be the self.…
              “He doesn’t assume fabrications to be the self.…
              “He doesn’t assume consciousness to be the self, or the self as possessing consciousness, or consciousness as in the self, or the self as in consciousness. This is how self-identification view does not come about.”
              The Noble Eightfold Path:
              “Now, again, lady, what is the noble eightfold path?”
              “This is the noble eightfold path, friend Visākha: right view, right resolve, right speech, right action, right livelihood, right effort, right mindfulness, right concentration.”
              “Is the noble eightfold path fabricated or unfabricated?”
              “The noble eightfold path is fabricated.”
              “And are the three aggregates [of virtue, concentration, & discernment] included under the noble eightfold path, lady, or is the noble eightfold path included under the three aggregates?”
              “The three aggregates are not included under the noble eightfold path, friend Visākha, but the noble eightfold path is included under the three aggregates. Right speech, right action, & right livelihood come under the aggregate of virtue. Right effort, right mindfulness, & right concentration come under the aggregate of concentration. Right view & right resolve come under the aggregate of discernment.”
              “Now what is concentration, lady, what qualities are its themes, what qualities are its requisites, and what is its development?”
              “Singleness of mind is concentration, friend Visākha; the four establishings of mindfulness are its themes; the four right exertions are its requisites; and any cultivation, development, & pursuit of these qualities is its development.”
              Fabrications:
              “Now, lady, what are fabrications?”
              “These three fabrications, friend Visākha: bodily fabrications, verbal fabrications, & mental fabrications.”
              “But what are bodily fabrications? What are verbal fabrications? What are mental fabrications?”
              “In-&-out breaths are bodily fabrications. Directed thought & evaluation are verbal fabrications. Perceptions & feelings are mental fabrications.”
              “But why are in-&-out breaths bodily fabrications? Why are directed thought & evaluation verbal fabrications? Why are perceptions & feelings mental fabrications?”
              “In-&-out breaths are bodily; these are things tied up with the body. That’s why in-&-out breaths are bodily fabrications. Having first directed one’s thoughts and made an evaluation, one then breaks out into speech. That’s why directed thought & evaluation are verbal fabrications. Perceptions & feelings are mental; these are things tied up with the mind. That’s why perceptions & feelings are mental fabrications.”
              “Now, lady, how does the attainment of the cessation of perception & feeling come about?”
              “The thought does not occur to a monk as he is attaining the cessation of perception & feeling that ‘I am about to attain the cessation of perception & feeling’ or that ‘I am attaining the cessation of perception & feeling’ or that ‘I have attained the cessation of perception & feeling.’ Instead, the way his mind has previously been developed leads him to that state.”
              “But when a monk is attaining the cessation of perception & feeling, which things cease first: bodily fabrications, verbal fabrications, or mental fabrications?”
              “When a monk is attaining the cessation of perception & feeling, friend Visākha, verbal fabrications cease first, then bodily fabrications, then mental fabrications.”
              “Now, lady, how does emergence from the cessation of perception & feeling come about?”
              “The thought does not occur to a monk as he is emerging from the cessation of perception & feeling that ‘I am about to emerge from the cessation of perception & feeling’ or that ‘I am emerging from the cessation of perception & feeling’ or that ‘I have emerged from the cessation of perception & feeling.’ Instead, the way his mind has previously been developed leads him to that state.”
              “But when a monk is emerging from the cessation of perception & feeling, which things arise first: bodily fabrications, verbal fabrications, or mental fabrications?”
              “When a monk is emerging from the cessation of perception & feeling, friend Visākha, mental fabrications arise first, then bodily fabrications, then verbal fabrications.”
              “When a monk has emerged from the cessation of perception & feeling, lady, how many contacts make contact?”
              “When a monk has emerged from the cessation of perception & feeling, friend Visākha, three contacts make contact: contact with emptiness, contact with the theme-less, & contact with the undirected.”
              “When a monk has emerged from the cessation of perception & feeling, lady, to what does his mind lean, to what does it tend, to what does it incline?”
              “When a monk has emerged from the cessation of perception & feeling, friend Visākha, his mind leans to seclusion, tends to seclusion, inclines to seclusion.”
              Feeling:
              “Now, lady, how many kinds of feeling are there?”
              “These three kinds of feeling: pleasant feeling, painful feeling, & neither-pleasant-nor-painful feeling.”
              “What is pleasant feeling? What is painful feeling? What is neither-pleasant-nor-painful feeling?”
              “Whatever is experienced physically or mentally as pleasant & gratifying is pleasant feeling. Whatever is experienced physically or mentally as painful & hurting is painful feeling. Whatever is experienced physically or mentally as neither gratifying nor hurting is neither-pleasant-nor-painful feeling.”
              “In what way is pleasant feeling pleasant, lady, and in what way painful? In what way is painful feeling painful, and in what way pleasant? In what way is neither-pleasant-nor-painful feeling pleasant, and in what way painful?”
              “Pleasant feeling is pleasant in remaining, & painful in changing, friend Visākha. Painful feeling is painful in remaining & pleasant in changing. Neither-pleasant-nor-painful feeling is pleasant in occurring together with knowledge, and painful in occurring without knowledge.”
              “What obsession gets obsessed with pleasant feeling? What obsession gets obsessed with painful feeling? What obsession gets obsessed with neither-pleasant-nor-painful feeling?”
              “Passion-obsession gets obsessed with pleasant feeling. Resistance-obsession gets obsessed with painful feeling. Ignorance-obsession gets obsessed with neither-pleasant-nor-painful feeling.”
              “Does passion-obsession get obsessed with all pleasant feeling? Does resistance-obsession get obsessed with all painful feeling? Does ignorance-obsession get obsessed with all neither-pleasant-nor-painful feeling?”
              “No.…”
              “But what is to be abandoned with regard to pleasant feeling? What is to be abandoned with regard to painful feeling? What is to be abandoned with regard to neither-pleasant-nor-painful feeling?”
              “Passion-obsession is to be abandoned with regard to pleasant feeling. Resistance-obsession is to be abandoned with regard to painful feeling. Ignorance-obsession is to be abandoned with regard to neither-pleasant-nor-painful feeling.”
              “Is passion-obsession to be abandoned with regard to all pleasant feeling? Is resistance-obsession to be abandoned with regard to all painful feeling? Is ignorance-obsession to be abandoned with regard to all neither-pleasant-nor-painful feeling?”
              “No .… There is the case where a monk, quite secluded from sensuality, secluded from unskillful qualities, enters & remains in the first jhāna: rapture & pleasure born of seclusion, accompanied by directed thought & evaluation. With that he abandons passion. No passion-obsession gets obsessed there. There is the case where a monk considers, ‘O when will I enter & remain in the dimension that those who are noble now enter & remain in?’ And as he thus nurses this yearning for the unexcelled liberations, there arises within him sorrow based on that yearning. With that he abandons resistance. No resistance-obsession gets obsessed there. There is the case where a monk, with the abandoning of pleasure & pain, as with the earlier disappearance of elation & distress, enters & remains in the fourth jhāna: purity of equanimity & mindfulness, neither pleasure nor pain. With that he abandons ignorance. No ignorance-obsession gets obsessed there.”
              “Now what, lady, lies on the other side of pleasant feeling?”
              “Passion lies on the other side of pleasant feeling.”
              “And what lies on the other side of painful feeling?”
              “Resistance lies on the other side of painful feeling.”
              “What lies on the other side of neither-pleasant-nor-painful feeling?”
              “Ignorance lies on the other side of neither-pleasant-nor-painful feeling.”
              “What lies on the other side of ignorance?”
              “Clear knowing lies on the other side of ignorance.”
              “What lies on the other side of clear knowing?”
              “Release lies on the other side of clear knowing.”
              “What lies on the other side of release?”
              “Unbinding lies on the other side of release.”
              “What lies on the other side of unbinding?”
              “You’ve gone too far, friend Visākha. You can’t keep holding on up to the limit of questions. For the holy life gains a footing in unbinding, culminates in unbinding, has unbinding as its final end. If you wish, go to the Blessed One and ask him the meaning of these things. Whatever he says, that’s how you should remember it.”
              Then Visākha the lay follower, delighting & rejoicing in what Dhammadinnā the nun had said, bowed down to her and, keeping her to his right, went to the Blessed One. On arrival, having bowed down to the Blessed One, he sat to one side. As he was sitting there he told the Blessed One the full extent of the conversation he had had with Dhammadinnā the nun. When this was said, the Blessed One said to him, “Dhammadinnā the nun is wise, Visākha, a woman of great discernment. If you had asked me those things, I would have answered you in the same way she did. That is the meaning of those things. That is how you should remember it.”
              That is what the Blessed One said. Gratified, Visākha the lay follower delighted in the Blessed One’s words.`,
    source: "MN 44",
    sourceUrl: "https://www.dhammatalks.org/suttas/MN/MN44.html",
    category: "Meditation",
  },
];
