name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npx vite build
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          # Verify SSH connection
          ssh -T $DEPLOY_USER@$DEPLOY_HOST -o StrictHostKeyChecking=accept-new exit || exit 1
          
          # First copy to temporary location on host
          rsync -avz --delete dist/ $DEPLOY_USER@$DEPLOY_HOST:/tmp/voice-web-dist/
          
          # Then copy from host into container
          ssh $DEPLOY_USER@$DEPLOY_HOST 'docker cp /tmp/voice-web-dist/. ed6360a20cbf:/var/www/voice.mettabit.io/'