name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npx vite build
        
      - name: Setup SSH
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          # Using port 2222
          ssh-keyscan -H -p 2222 $DEPLOY_HOST >> ~/.ssh/known_hosts 2>/dev/null
          chmod 644 ~/.ssh/known_hosts
          
      - name: Deploy
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          rsync -avz --delete -e "ssh -p 2222 -i ~/.ssh/deploy_key" \
            dist/ \
            ${DEPLOY_USER}@${DEPLOY_HOST}:/home/${DEPLOY_USER}/docker/voice/data/
          
          ssh -p 2222 -i ~/.ssh/deploy_key ${DEPLOY_USER}@${DEPLOY_HOST} \
            "cd /home/${DEPLOY_USER}/docker/voice && docker-compose down && docker-compose up -d"